# Generated by Django 5.2.2 on 2025-06-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lostitem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datereported', models.DateField(db_column='DateReported')),
                ('timereported', models.TimeField(db_column='TimeReported')),
                ('isclaimed', models.CharField(db_column='IsClaimed', max_length=1)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=255, null=True)),
            ],
            options={
                'db_table': 'LostItem',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Lostitemreport',
        ),
    ]
