# Generated by Django 5.2.2 on 2025-06-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lostitem_delete_lostitemreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostitem',
            options={'managed': True},
        ),
    ]
