# Generated by Django 5.2.2 on 2025-06-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lostitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostitem',
            options={'managed': False},
        ),
    ]
